//TODO: convert to a Mongoose Model Schema
export enum Tribe {
  BEAR = 'BEAR',
  BULL = 'BULL',
  CROCODILE = 'CROCODILE',
  DOG = 'DOG',
  EAGLE = 'EAGLE',
  ELEPHANT = 'ELEPHANT',
  FOX = 'FOX',
  GOAT = 'GOAT',
  HYENA = 'HYENA',
  LEOPARD = 'LEOPARD',
  LION = 'LION',
  RABBIT = 'RABBIT',
  RHYNO = 'RHYNO',
  ROOSTER = 'ROOSTER',
  SHARK = 'SHARK',
  TIGER = 'TIGER',
  WHALE = 'WHALE',
  WHITE_TIGER = 'WHITE_TIGER',
  WOLF = 'WOLF',
}
